#!/usr/bin/env bash

# Update package lists
# Install Nginx (use -y flag for unattended installation)
# Create a basic HTML file with "Hello World!" content
# use service command for restarting

sudo apt-get -y  update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
