#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page 
# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx traffic through firewall (assuming UFW is used)
sudo ufw allow 'Nginx HTTP'

# Create a placeholder index file
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# --- Redirection Rule ---
sed -i '/^\s*server\s*{/i \    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload
