#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page 
# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx traffic through firewall (assuming UFW is used)
sudo ufw allow 'Nginx HTTP'

# Create a placeholder index file
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Configure redirection in default Nginx configuration
sudo sed -i '/listen 80 default_server/a return 301 https://www.youtube.com;' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload
