#!/usr/bin/env bash
# Add a custom header named X-Served-By with the server's hostname
sudo apt-get -y update
sudo apt-get install -y nginx 

echo "Hello World!" >  /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   add_header X-Served-By $HOSTNAME;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
