#!/usr/bin/env bash
# prints a string 10 times displays, bad luck for the 4th loop iteration good luck for the 8th loop iteration and Best School for the other iterations

i=1

while [ "$i" -lt 10 ]; do


  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi


  ((i++))
done
