#!/usr/bin/env bash
# Prints numbers from 1 to 20 and displays "bad luck" messages for the 4th, 9th, and 17th loop iterations with countries specified.


i=1

while [ "$i" -le 20 ]; do
    echo "$i"

    case $i in 
        4)
            echo "Bad luck from China";;
        9) 
            echo "Bad luck from Japan";;
        17 )
            echo "Bad luck from Italy";;
        *) ;;
    esac 

    ((i++))
done