#!/usr/bin/env bash

# SSH connection script

# Set the path to the private key
private_key="~/.ssh/school"

# Set the username and server IP
username="ubuntu"
server_ip="54.210.195.96"

# SSH connection command
ssh -i "$private_key" "$username@$server_ip"

