#!/usr/bin/env bash

# Create an RSA key pair with specific requirements

# Set the name of the private key
private_key="school"

# Set the number of bits for the key
bits="4096"

# Set the passphrase for the key
passphrase="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b "$bits" -f "$private_key" -N "$passphrase"

echo "RSA key pair created successfully."

